services:
  api:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Souleater11#  
      - MYSQL_DATABASE=mydatabase
    depends_on:
      - mysql_db
    volumes:
      - .:/app  
      
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Souleater11#  
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: